### PR TITLE
fix: use Input in ComponentTable

### PR DESCRIPTION
**Pull request by rikkebl**
## Why is this pull request needed?
To accept decimalnumbers on format 0.01

## What does this pull request change?
Changed from Textfield to Input in ComponentTable. 
Removed toString(). 

## Issues related to this change:
#157

### CODE REVIEW

**Review by mariuswinger — APPROVED** [review]
Nice! Should we do this for the other number input fields as well?

**Comment by rikkebl** [comment]
Tried to use it on temperature and pressure, but the Input don't support the warning helpertext.

**Comment by soofstad** [comment]
Could add some custom "helperText" then. But not sure how bad these TextFields behave right now, if its worth it or not

**Comment by rikkebl** [comment]
I'll just merge this now, and we could discuss that later

**Pull request merged**
